# Generated by Django 6.0.5 on 2026-05-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0003_cablepurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(choices=[('ikeja-electric', 'Ikeja Electric'), ('eko-electric', 'Eko Electric'), ('abuja-electric', 'Abuja Electric'), ('kano-electric', 'Kano Electric'), ('portharcourt-electric', 'Port Harcourt Electric'), ('jos-electric', 'Jos Electric'), ('ibadan-electric', 'Ibadan Electric'), ('kaduna-electric', 'Kaduna Electric'), ('enugu-electric', 'Enugu Electric'), ('benin-electric', 'Benin Electric'), ('aba-electric', 'Aba Electric'), ('yola-electric', 'Yola Electric')], max_length=50)),
                ('meter_number', models.CharField(max_length=20)),
                ('meter_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
