# Generated by Django 6.0.5 on 2026-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_datapurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPurchase',
        ),
    ]
